
x-superset-image: &superset-image apachesuperset.docker.scarf.sh/apache/superset:${TAG:-latest-dev}

version: "3.9"
services:

  superset:
    env_file: docker_superset/.env
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    volumes: 
     - ./docker_superset:/app/docker
     - superset_home:/app/superset_home

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker_superset/.env
    user: "root"
    volumes:
      - ./docker_superset:/app/docker
      - superset_home:/app/superset_home
    healthcheck:
      disable: true

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker_superset/.env
    restart: unless-stopped
    user: "root"
    volumes: 
     - ./docker_superset:/app/docker
     - superset_home:/app/superset_home
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
